var codropsEvents = {

/*April */	


'04-01-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><p style="text-align: left;">(i)</p><math><semantics><mrow><msqrt><mrow><mn>11.56</mn></mrow></msqrt></mrow></semantics></math><p style="text-align: left;">(ii)</p><math><semantics><mrow><msup><mrow><mn>5.4</mn></mrow><mn>2</mn></msup></mrow></semantics></math></div><div class="questiontext"><p>Write down the value of the above</p></div></div><div class="answer"><div class="answercontainer"><p style="text-align: left;">(i)</p><math><semantics><mrow><msqrt><mrow><mn>11.56</mn></mrow></msqrt></mrow></semantics></math><p style="text-align: left;">(ii)</p><math><semantics><mrow><msup><mrow><mn>5.4</mn></mrow><mn>2</mn></msup></mrow></semantics></math></div><div class="answertext"><p>Answer will appear here!</p></div></div></a>',
'04-02-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><math><semantics><mrow><mo stretchy="false">(</mo><mn>5.4</mn><mo>&#x00D7;</mo><msup><mrow><mn>10</mn></mrow><mn>3</mn></msup><mo stretchy="false">)</mo><mo>&#x00D7;</mo><mo stretchy="false">(</mo><mn>3</mn><mo>&#x00D7;</mo><msup><mrow><mn>10</mn></mrow><mn>5</mn></msup><mo stretchy="false">)</mo></mrow></semantics></math><div class="questiontext"><p>Question</p></div></div></div><div class="answer"><div class="answercontainer"><p>Answer will appear here!</p></div><div class="answertext"><p>Answer will appear here!</p></div></div></a>',
'04-03-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut07_181_01_1a.png"><p>Geraint buys a pair of jeans for £22.49 and a polo shirt for £13.87.</p></div><div class="questiontext"><p> Find the total cost of these two items.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut07_181_01_1a.png"><p>Geraint buys a pair of jeans for £22.49 and a polo shirt for £13.87.</p></div><div class="answertext"><p>£22.49 + £13.87 = £36.36</p></div></div></a>',
'04-04-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut07_181_01_10.png"><p>The diagram above shows a right-angled triangle with one angle of 67°.</p></div><div class="questiontext"><p>Find the value of x?</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut07_181_01_10.png"  ></div><div class="answertext"><p>180° - 90° - 67° = 23°</p></div></div></a>',
'04-05-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut07_181_01_4b.png"><p>The bar chart shows the number of pupils absent each day in a particular week.</p></div><div class="questiontext"><p> How many absences, in total, were recorded for that week?</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut07_181_01_4b.png"  ><p>The bar chart shows the number of pupils absent each day in a particular week.</p></div><div class="answertext"><p>How many absences, in total, were recorded for that week? 4+5+2+3+4 = 18</p></div></div></a>',
'04-06-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut07_181_01_5a.png"></div><div class="questiontext"><p>Write down the two lines in the above diagram,<br> which are perpendicular to each other.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut07_181_01_5a.png"></div><div class="answertext"><p>AB, BC <br>(Two lines are perpendicular if they meet at a right angle, or at 90°)</p></div></div></a>',
'04-07-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut07_181_01_7b.png"></div><div class="questiontext"><p>Write down the area of the rectangle shown above.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut07_181_01_7b.png"></div><div class="answertext"><p>5cm × 7cm = 35cm²</p></div></div></a>',
'04-08-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><p><math><mrow><mn>4</mn><mi>a</mi><mtext>&#x00A0;</mtext><mo>+</mo><mtext>&#x00A0;</mtext><mn>7</mn><mi>a</mi><mtext>&#x00A0;</mtext><mo>+</mo><mtext>&#x00A0;</mtext><mn>8</mn><mi>a</mi></mrow></math></p></div><div class="questiontext"><p>Simplify the equation above.</p></div></div><div class="answer"><div class="answercontainer"><p><math><mrow><mn>4</mn><mi>a</mi><mtext>&#x00A0;</mtext><mo>+</mo><mtext>&#x00A0;</mtext><mn>7</mn><mi>a</mi><mtext>&#x00A0;</mtext><mo>+</mo><mtext>&#x00A0;</mtext><mn>8</mn><mi>a</mi></mrow></math></p></div><div class="answertext"><p><math><mrow><mn>19</mn><mi>a</mi></mrow></math></p></div></div></a>',
'04-09-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><p><img src="images/cool-boots.png"></p></div><div class="questiontext"><p>Write down the value of the cube of 5.</p></div></div><div class="answer"><div class="answercontainer"><p><img src="images/cool-boots.png"></p></div><div class="answertext"><p>5³ = 5 × 5 × 5 = 25 × 5 = 125.</p></div></div></a>',
'04-10-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><p>1 4 9 16</p></div><div class="questiontext"><p>Write down, in terms of n, the nth term of the sequence shown above.</p></div></div><div class="answer"><div class="answercontainer"><p>1 4 9 16</p></div><div class="answertext"><p>n squared</p></div></div></a>',
'04-11-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><p><table><tr><th>Name of three-dimensional solid</th><th>Number of triangular faces</th><th>Number of square rectangler faces</th><th>Number of exagonal faces</th></tr><tr><td>Square- based pyramid</td><td></td><td></td><td></td></tr><tr><td>Tetrahedron</td><td></td><td></td><td></td></tr><tr><td>Hexagonal prism</td><td></td><td></td><td></td></tr></table></p></div><div class="questiontext"><p>Complete the table shown above.</p></div></div><div class="answer"><div class="answercontainer"><p><table><tr><th>Name of three-dimensional solid</th><th>Number of triangular faces</th><th>Number of square rectangler faces</th><th>Number of exagonal faces</th></tr><tr><td>Square- based pyramid</td><td>4</td><td>1</td><td>0</td></tr><tr><td>Tetrahedron</td><td>4</td><td>0</td><td>0</td></tr><tr><td>Hexagonal prism</td><td>0</td><td>6</td><td>2</td></tr></table></p></div></div></a>',
'04-12-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><p>0.2 x 0.3</p></div><div class="questiontext"><p>Find the value of the equation shown above</p></div></div><div class="answer"><div class="answercontainer"><p>0.2 x 0.3</p></div><div class="answertext"><p>2/10 × 3/10 = 6/100 = 0.06</p></div></div></a>',
'04-13-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut07_184_05_10a.png"><p>In the diagram above, ABCD is a trapezium with AD parallel to BC. The lengths of AD and BC are 30cm and 20cm respectively. The perpendicular distance between the parallel sides is 22cm.</p></div><div class="questiontext"><p> Calculate the area of the trapezium and clearly write down the units of your answer.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut07_184_05_10a.png"></div><div class="answertext"><p>20 + 30 = 50. 50 ÷ 2 = 25. 25 × 22 = 550cm²</p></div></div></a>',
'04-14-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/cool-boots.png"></div><div class="questiontext"><p>Convert 54 000 cm2 into m2.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/cool-boots.png"></div><div class="answertext"><p>54000 ÷ 100 = 540. 540 ÷ 100 = 5.4 m². <br> With area we must divide by the scale factor (100) twice.</p></div></div></a>',
'04-15-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><p><table><tr><td>x</td><td>-2</td><td>-1</td><td>0</td><td>1</td><td>2</td><td>3</td></tr><tr><td><math><mrow><mi>y</mi><mo>=</mo><mn>3</mn><msup><mi>x</mi><mn>3</mn></msup><mtext>&#x00A0;</mtext><mo>&#x2212;</mo><mtext>&#x00A0;</text><mn>4</mn><mi>x</mi><mtext>&#x00A0;</mtext><mo>&#x2212;</mo><mtext>&#x00A0;</mtext><mn>10</mn></mrow></math></td><td>10</td><td></td><td>-10</td><td>-11</td><td>-6</td><td>5</td></tr></table></p></div><div class="questiontext"><p>The table shows some of the values of y = 3x2 – 4x – 10 for values of x between – 2 and 3.</p></div></div><div class="answer"><div class="answercontainer"><p><table><tr><td>x</td><td>-2</td><td>-1</td><td>0</td><td>1</td><td>2</td><td>3</td></tr><tr><td><math><mrow><mi>y</mi><mo>=</mo><mn>3</mn><msup><mi>x</mi><mn>3</mn></msup><mtext>&#x00A0;</mtext><mo>&#x2212;</mo><mtext>&#x00A0;</text><mn>4</mn><mi>x</mi><mtext>&#x00A0;</mtext><mo>&#x2212;</mo><mtext>&#x00A0;</mtext><mn>10</mn></mrow></math></td><td>10</td><td></td><td>-10</td><td>-11</td><td>-6</td><td>5</td></tr></table></p></div><div class="answertext"><p>3 × (-1)² - 4 × -1 - 10 = 3 × 1 - -4 - 10 = 3 + 4 - 10 = -3</p></div></div></a>',
'04-16-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><p>Find the Value of <br><math display="block"><mrow><mfrac><mn>5</mn><mn>6</mn></mfrac><mo>&#x2212;</mo><mfrac><mn>1</mn><mn>4</mn></mfrac></mrow></math></p></div></div><div class="answer"><div class="answercontainer"><math display="block"><mrow><mfrac><mn>5</mn><mn>6</mn></mfrac><mo>&#x2212;</mo><mfrac><mn>1</mn><mn>4</mn></mfrac><mo>=</mo><mfrac><mrow><mn>10</mn></mrow><mrow><mn>12</mn></mrow></mfrac><mo>&#x2212;</mo><mfrac><mn>3</mn><mrow><mn>12</mn></mrow></mfrac><mo>=</mo><mfrac><mn>7</mn><mrow><mn>12</mn></mrow></mfrac></mrow></math></div></div></a>',
'04-17-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut07_184_05_3c.png"></div><div class="questiontext"><p>Calculate, in mph, the speed of a motorcyclist who travels 154 miles in 3 hours, 30 minutes.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut07_184_05_3c.png"></div><div class="answertext"><p>154 ÷ 3.5 = 44 m.p.h.</p></div></div></a>',
'04-18-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut07_184_05_5b.png"></div><div class="questiontext"><p>Find the size of the angle marked y.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut07_184_05_5b.png"></div><div class="questiontext"><p>115° + 88° + 82° = 285°. 360° - 285° = 75°. 180° - 75° = 105°</p></div></div></a>',
'04-19-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><p>Write each of the following numbers in standard form.<br> (i) 0·0083 <br>(ii) 7 500000000</p></div></div><div class="answer"><div class="answercontainer"> <math display="block"><mrow><mo stretchy="false">(</mo><mi>i</mi><mo stretchy="false">)</mo><mtext>&#x00A0;</mtext><mn>4.98</mn><mtext>&#x00A0;</mtext><mi>x</mi><mtext>&#x00A0;</mtext><msup><mrow><mn>10</mn></mrow><mrow><msup><mrow></mrow><mrow><mn>7</mn><mtext>&#x00A0;&#x00A0;&#x00A0;</mtext></mrow></msup></mrow></msup><mtext>&#x00A0;&#x00A0;&#x00A0;&#x00A0;&#x00A0;&#x00A0;&#x00A0;&#x00A0;</mtext><mo stretchy="false">(</mo><mi>i</mi><mi>i</mi><mo stretchy="false">)</mo><mn>3</mn><mtext>&#x00A0;</mtext><mi>x</mi><mtext>&#x00A0;</mtext><mn>10</mn><msup><mtext>&#x00A0;</mtext><mrow><mo>-</mo><mn>6</mn></mrow></msup></mrow></math></div></div></a>',
'04-20-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><p>Find, in standard form, the value of</p><br> <math display="block"><mrow><mo stretchy="false">(</mo><mn>2.66</mn><mo>&#x00A0;</mo><mo>&#x00D7;</mo><msup><mrow>    <mn>10</mn></mrow><mn>9</mn></msup><mo stretchy="false">)</mo><mo>&#x00F7;</mo><mo stretchy="false">(</mo><mn>7.6</mn><mo>&#x00D7;</mo><msup><mrow><mn>10</mn></mrow><mrow><mo>&#x2212;</mo><mn>3</mn></mrow></msup><mo stretchy="false">)</mo></mrow></math></div></div><div class="answer"><div class="answercontainer"><math display="block"><mrow><mtext>8</mtext><msup><mrow><mtext>.846&#x00A0;x&#x00A0;10</mtext></mrow><mtext>9</mtext></msup></mrow></math></div></div></a>',
'04-21-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><math display="block"><mrow><mtext>2</mtext><mfrac><mn>1</mn><mn>4</mn></mfrac><mo>&#x00D7;</mo><mn>3</mn><mfrac><mn>1</mn><mn>3</mn></mfrac></mrow></math></div></div><div class="answer"><div class="answercontainer"><p>7½ ("The fraction 90/12 can be simplified to give 15/2, or 7½")</p></div></div></a>',
'04-22-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><math display="block"><mrow><msup><mn>8</mn><mn>0</mn></msup></mrow></math></div><div class="questiontext"><p>Simplify the equation above.</p></div></div><div class="answer"><div class="answercontainer"><math display="block"><mrow><msup><mn>8</mn><mn>0</mn></msup></mrow></math></div><div class="answertext"><p>Any number to the power 0 is equal to 1.</p></div></div></a>',
'04-23-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><p>There are 100 pupils in Year 9. The time taken by each pupil to answer a mental mathematics</p><img src="images/Aut07-184-09-19a.png"></div><div class="questiontext"><p>Find an estimate of this distribution</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut07-184-09-19a.png"></div><div class="answertext"><p>100 ÷ 2 = 50.<br> There are 50 pupils in the first three groups, and 50 in the final two groups.<br> The median is therefore 30 seconds.</p></div></div></a>',
'04-24-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/money-notes-uk.jpg"></div><div class="questiontext"><p>Find 40% of £120.</p></div></div><div class="answer"><div class="answercontainer"> <img src="images/money-notes-uk.jpg"></div><div class="answertext"><p>10% of £120 = £12. So 40% of £120 is   4 × £12 = £48.</p></div></div></a>',
'04-25-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><p><br><math display="block"><mrow><msup><mrow><mo stretchy="false">(</mo><mn>0.5</mn><mo stretchy="false">)</mo></mrow><mn>2</mn></msup></mrow></math></div><div class="questiontext"><p>Write down the value of the equation above</p></div></div><div class="answer"><div class="answercontainer"><math display="block"><mrow><msup><mrow><mo stretchy="false">(</mo><mn>0.5</mn><mo stretchy="false">)</mo></mrow><mn>2</mn></msup><mtext>=&#x00A0;0</mtext><mtext>.5</mtext><mo>&#x00D7;</mo><mn>0.5</mn><mo stretchy="false">(</mo><mfrac>  <mn>1</mn><mn>2</mn></mfrac><mo>&#x00D7;</mo><mfrac><mn>1</mn><mn>2</mn></mfrac><mo>=</mo><mfrac><mn>1</mn><mn>4</mn>  </mfrac><mo stretchy="false">)</mo></mrow></math></div></div></a>',
'04-26-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/cool-boots.png"></div><div class="questiontext"><p>Steven has £50 to spend on computer games. Each game costs £7.89.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/cool-boots.png"></div><div class="answertext"><p>50÷7.79 = 6.337, so 6 whole games</p></div></div></a>',
'04-27-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/cool-boots.png"></div><div class="questiontext"><p>Sarah buys 4 CDs. They cost £5.86 each. How much change will she be given from £30?</p></div></div><div class="answer"><div class="answercontainer"><img src="images/cool-boots.png"></div><div class="answertext"><p>4 x 5.86 = 23.44  30 - 23.44 = £6.56</p></div></div></a>',
'04-28-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/cool-boots.png"></div><div class="questiontext"><p>Write down the name of a four-sided shape which has rotational symmetry of order 4.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/cool-boots.png"></div><div class="answertext"><p>square</p></div></div></a>',
'04-29-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut08_181_02_13a.png"  ></div><div class="questiontext"><p>Write down the size of the angle marked x in the following diagram.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut08_181_02_13a.png"></div><div class="answertext"><p>128</p></div></div></a>',
'04-30-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut08_181_02_13b.png"  ></div><div class="questiontext"><p>Calculate the area of the triangle shown above.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut08_181_02_13b.png"></div><div class="answertext"><p>Area of a triangle is 1/2(base x height), 1/2(12 x 8) = 1/2(96)=48cm2</p></div></div></a>',
'04-31-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/money-notes-uk.jpg"></div><div class="questiontext"><p>3 8 11 16 19 24 27 From the list of numbers given above: write down a square number write down a multiple of 6 write down a factor of 40 </p></div></div><div class="answer"><div class="answercontainer"><p>from top: 16, 24, 8</p></div></div></a>',


/*MAY */	



'05-01-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/cool-boots.png"></div><div class="questiontext"><p>Write 2472<br>(i) correct to the nearest 10 <br>(ii) correct to the nearest 100</div></div><div class="answer"><div class="answercontainer"><img src="images/cool-boots.png"></div><div class="answertext"><p>Answer will appear here!</p></div></div></a>',
'05-02-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut07_181_02_5.png"></div><div class="questiontext"><p>Write down two pairs of congruent shapes from the diagrams above.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut07_181_02_5.png"></div><div class="answertext"><p>B and I, E and J</p></div></div></a>',
'05-03-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><p>(i) 3, 9, 15, 21, ????<br> (ii) 20, 17, 14, 11, ????</p></div><div class="questiontext"><p> <br> Write down the next number in the sequences above. </p></div></div><div class="answer"><div class="answercontainer"><p>(i) 3, 9, 15, 21, ????<br> (ii) 20, 17, 14, 11, ????</p></div><div class="answertext"><p>(i) rule is  + 6   = 27 <br>(ii) rule is -3 = 8</p></div></div></a>',
'05-04-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><p>2, 9, 16, 23,</p></div><div class="questiontext"><p>Describe, in words, the rule for finding the next number in the sequence given above.</p></div></div><div class="answer"><div class="answercontainer"><p>2, 9, 16, 23,</p></div><div class="answertext"><p>add seven </p></div></div></a>',
'05-05-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><p>Cost = £35 × Number of Hours + Call-out Charge</p></div><div class="questiontext"><p>The formula shown above is used to calculate the cost of repairing washing machines. Calculate the Cost when the Number of Hours is 3 and the Call-out Charge is £40.</p></div></div><div class="answer"><div class="answercontainer"><p>The formula shown above is used to calculate the cost of repairing washing machines. Calculate the Cost when the Number of Hours is 3 and the Call-out Charge is £40.</p></div><div class="answertext"><p>35 x 3 + 40 = £145</p></div></div></a>',
'05-06-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut08_181_02_8b.png"></div><div class="questiontext"><p>In the diagram shown above, AOB is a straight line.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut08_181_02_8b.png"></div><div class="answertext"><p>angles on a straight line add up to 180, 180 -  43 - 108 = 29</p></div></div></a>',
'05-07-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">MathMl of expression (see question)</div><div class="questiontext"><p>Find, correct to 3 significant figures, the value of the expression shown above.</p></div></div><div class="answer"><div class="answercontainer">MathMl of expression (see question)</div><div class="answertext"><p>5.62</p></div></div></a>',
'05-08-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><p>2a + 7b</p></div><div class="questiontext"><p>What is the value of  the equation above when a = 6 and b = –2?</p></div></div><div class="answer"><div class="answercontainer"><p>2a + 7b</p></div><div class="answertext"><p>2 x 6 + 7 x (-2) = 12 - 14 = -2</p></div></div></a>',
'05-09-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><p>32, 30, 26, 20, 12,</p></div><div class="questiontext"><p>Write down the next two numbers in the sequence shown above.</p></div></div><div class="answer"><div class="answercontainer"><p>32, 30, 26, 20, 12,</p></div><div class="answertext"><p>look at the difference between each term, -2, -4, -6,-8,  therefore -10 for the next term and -12 for the one after = 2,  -10</p></div></div></a>',
'05-10-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut08_181_04_5a.png"></div><div class="questiontext"><p>The diagram above represents a number machine.   <br> (i) When the INPUT is 7, what is the OUTPUT?  <br> (ii) When the OUTPUT is 30, what is the INPUT?  <br> (iii) If the INPUT is n, write down the OUTPUT in terms of n.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut08_181_04_5a.png"></div><div class="answertext"><p>(i)20 (ii) 9 (iii)5(n -3)</p></div></div></a>',
'05-11-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">MathMl: 5(2x – 3) = 20.</div><div class="questiontext"><p>Solve the equation above.</p></div></div><div class="answer"><div class="answercontainer">MathMl: 5(2x – 3) = 20.</div><div class="answertext"><p>10x = 35, x = 35÷10 = 3.5</p></div></div></a>',
'05-12-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">TBD</div><div class="questiontext"><p>Calculate, to 1 decimal place, the area of a circle whose radius is 12·3 cm, clearly stating the units of your answer.</p></div></div><div class="answer"><div class="answercontainer">Calculate, to 1 decimal place, the area of a circle whose radius is 12·3 cm, clearly stating the units of your answer.</div><div class="answertext"><p>Area of a circle = πr2, π x 12.32 = 475.3</p></div></div></a>',
'05-13-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">PIC WAITING - Aut08-181/04-7(a)</div><div class="questiontext"><p>A packet of nails costs £2 and a packet of screws costs £3. Andrew buys 4 packets of nails and x packets of screws for a total of £23.</p></div></div><div class="answer"><div class="answercontainer">PIC WAITING - Aut08-181/04-7(a)<p>A packet of nails costs £2 and a packet of screws costs £3. Andrew buys 4 packets of nails and x packets of screws for a total of £23.</p></div><div class="answertext"><p>8 + 3x = 23</p></div></div></a>',
'05-14-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">PIC WAITING - Aut08-184/05-7(b)</div><div class="questiontext"><p>Share £56 in the ratio of 6:1.</p></div></div><div class="answer"><div class="answercontainer">PIC WAITING - Aut08-184/05-7</div><div class="answertext"><p>6 + 1 = 7. £56 ÷ 7 = £8. £8 × 6 = £48. £8 × 1 = £8.</p></div></div></a>',
'05-15-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut08_810_01_4b.png"></div><div class="questiontext"><p>A bag contains 4 balls which are identical except for their colour. There is 1 red, 1 yellow, 1 blue and 1 green ball. One ball is chosen at random from the bag. On the probability scale shown below, mark the points, A, B and C where: A is the probability that the chosen ball is green. B is the probability that the chosen ball is white. C is the probability that the chosen ball is not green.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut08_810_01_4b.png"></div><div class="answertext"><p>Need to create diagram with B, A and C labelled.</p></div></div></a>',
'05-16-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">PIC WAITING - Aut09-185/08-1(a)</div><div class="questiontext"><p>Alice buys 3 packets of biscuits at £1.35 each and 2 bars of muesli at 56p each. How much is this altogether?</p></div></div><div class="answer"><div class="answercontainer">PIC WAITING - Aut09-185/08-1(a)</div><div class="answertext"><p>3 x 1.35 = 4.05, 2 x 0.56 = 1.12, 4.05 + 1.12 = £5.17</p></div></div></a>',
'05-17-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">4c + 2c + 3c.</div><div class="questiontext"><p>Simplify</p></div></div><div class="answer"><div class="answercontainer">4c + 2c + 3c</div><div class="answertext"><p>9c</p></div></div></a>',
'05-18-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"> <br>(i) 3x = 15 <br> <br>(ii) y + 7 = 13 <br></div><div class="questiontext"><p>Solve each of the following equations.</p></div></div><div class="answer"><div class="answercontainer"> <br>(i) 3x = 15 <br>(ii) y + 7 = 13 <br></div><div class="answertext"><p> <br>(i) x = 15 <br> <br>(ii) y = 6 <br></p></div></div></a>',
'05-19-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">MathMl: R = 3V + 2T (Aut09-185/08-12(c))</div><div class="questiontext"><p>Use the formula  to find V when R = 40 and T = 5.</p></div></div><div class="answer"><div class="answercontainer">MathMl: R = 3V + 2T (Aut09-185/08-12(c)</div><div class="answertext"><p>40 = 3V + 2 x 5, 40 = 3V + 10, 3V = 30, V = 30÷10</p></div></div></a>',
'05-20-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">MathMl: formula (see question Aut09-185/08-15(b))</div><div class="questiontext"><p>Evaluate</p></div></div><div class="answer"><div class="answercontainer">MathMl: formula (see question Aut09-185/08-15(b))</div><div class="answertext"><p>24.09</p></div></div></a>',
'05-21-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut09_185_08_18bii.png"></div><div class="questiontext"><p>The diagram shows a quadrilateral.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut09_185_08_18bii.png"></div><div class="answertext"><p> x = 7 ©7cm, 9cm, 10cm, 14cm in any order</p></div></div></a>',
'05-22-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut09_185_08_2ciandii.png"></div><div class="questiontext"><p>What fraction of the following shape is shaded?</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut09_185_08_2ciandii.png"></div><div class="answertext"><p>9/14</p></div></div></a>',
'05-23-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut09_185_08_2ciandii.png"></div><div class="questiontext"><p>What fraction of the following shape is NOT shaded?</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut09_185_08_2ciandii.png"></div><div class="answertext"><p>5/14</p></div></div></a>',
'05-24-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">4x – 6</div><div class="questiontext"><p>Factorise </p></div></div><div class="answer"><div class="answercontainer">4x – 6</div><div class="answertext"><p>2(x - 3)</p></div></div></a>',
'05-25-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">(a) 50, 45, 40, 35, <br>(b) 2, 6, 18, 54,</div><div class="questiontext"><p>Describe in words the rule for continuing each of the following sequences.</p></div></div><div class="answer"><div class="answercontainer">(a) 50, 45, 40, 35, <br>(b) 2, 6, 18, 54,</div><div class="answertext"><p>(a) subtract 5 <br> (b) multiply by 3</p></div></div></a>',
'05-26-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut09_185_08_9b.png"></div><div class="questiontext"><p>Write down the special name given to an angle which is greater than 180° and less than 360°.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut09_185_08_9b.png"></div><div class="answertext"><p>Obtuse</p></div></div></a>',
'05-27-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">TBD (Aut09-185/10-4(a))</div><div class="questiontext"><p>Keith says that the sum of two different square numbers is always odd.</p></div></div><div class="answer"><div class="answercontainer">TBD (Aut09-185/10-4(a))</div><div class="answertext"><p>1,9 or 4,16 or 1,25 or 9,25</p></div></div></a>',
'05-28-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">TBD (Aut09-185/10-4(b))</div><div class="questiontext"><p>Janice says that prime numbers are always odd.</p></div></div><div class="answer"><div class="answercontainer">TBD (Aut09-185/10-4(b))</div><div class="answertext"><p>1st part:No <br> 2nd: 2</p></div></div></a>',
'05-29-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">9, 17, 25, 33, 41,</div><div class="questiontext"><p>Write down the nth term of the sequence </p></div></div><div class="answer"><div class="answercontainer">9, 17, 25, 33, 41,</div><div class="answertext"><p>8n + 1</p></div></div></a>',
'05-30-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut09_185_10_7b.png"></div><div class="questiontext"><p>A cyclist travels 28 miles in 1 hour 45 minutes, find her average speed in m.p.h.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut09_185_10_7b.png"></div><div class="answertext"><p>Speed = Distance ÷ time, 28 ÷ 1.75, = 16mph <br> remember that 1 hour 45 minutes is 1.75 hour NOT 1.45</p></div></div></a>',
'05-31-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">TBD (Aut09-185/11-1(c))</div><div class="questiontext"><p>Write down all the factors of 55.</p></div></div><div class="answer"><div class="answercontainer">TBD (Aut09-185/11-1(c))</div><div class="answertext"><p>The factors of 55 are all the numbers that divide into 55. <br> 1, 5, 11, 55</p></div></div></a>',


/*JUNE */	

'06-01-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut09_185_12_1c.png"></div><div class="questiontext"><p>(i)What percentage of the following shape is shaded? <br> (ii) What percentage of the shape is NOT shaded?</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut09_185_12_1c.png"></div><div class="answertext"><p>(i) 40% <br> (ii) 60%</p></div></div></a>',
'06-02-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">53 861 = ????</div><div class="questiontext"><p>Write down 53 861 correct to 3 significant figures.</p></div></div><div class="answer"><div class="answercontainer">53 861 = ????</div><div class="answertext"><p>53900</p></div></div></a>',
'06-03-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">0·2147 = ????</div><div class="questiontext"><p>Write down 0·2147 correct to 2 significant figures.</p></div></div><div class="answer"><div class="answercontainer">0·2147 = ????</div><div class="answertext"><p>0.21</p></div></div></a>',
'06-04-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">MathMl: equation (see question Aut09-185/12-16(b))</div><div class="questiontext"><p>Find the value of the equation above.</p></div></div><div class="answer"><div class="answercontainer">MathMl: equation (see question Aut09-185/12-16(b))</div><div class="answertext"><p>18.29</p></div></div></a>',
'06-05-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut09-185-12-17a.png"></div><div class="questiontext"><p>The table above shows the probabilities of selecting one ball at random from a bag of coloured balls.     Are there any balls of another colour in the bag? </p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut09-185-12-17a.png"></div><div class="answertext"><p>No</p></div></div></a>',
'06-06-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut09-185-12-17b.png"></div><div class="questiontext"><p>The table below shows the probabilities of selecting one ball at random from a bag of coloured balls. What is the probability of selecting  <br>  (i) either a yellow or a purple ball?  <br>  (ii) a ball of any colour other than white? <br>  </p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut09-185-12-17b.png"></div><div class="answertext"><p>(i) 0.46 <br>  (ii) 0.85</p></div></div></a>',
'06-07-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut09_185_12_2ai.png"></div><div class="questiontext"><p>How much does Molly’s pet hamster weigh?</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut09_185_12_2ai.png"></div><div class="answertext"><p>340g</p></div></div></a>',
'06-08-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut09_185_12_2b.png"></div><div class="questiontext"><p>Molly goes out in her car. What speed is she doing, correct to the nearest 10 miles per hour?</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut09_185_12_2b.png"></div><div class="answertext"><p>60mph</p></div></div></a>',
'06-09-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut09_185_12_3b.png"></div><div class="questiontext"><p>Write down the special name of the straight line shown in each diagram below.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut09_185_12_3b.png"></div><div class="answertext"><p>chord, diameter, tangent</p></div></div></a>',
'06-10-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut09_185_12_3c.png"></div><div class="questiontext"><p>Write down the name of each of the shapes shown above.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut09_185_12_3c.png"></div><div class="answertext"><p>1st row: trapezium, pentagon, 2nd row: cylinder</p></div></div></a>',
'06-11-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">Total Cost = Number of days × £6.75 + Hire charge.</div><div class="questiontext"><p>The formula to find the Total Cost, in pounds, of hiring a carpet cleaner is <br> (i) Find the Total Cost when the Number of days is 3 and the Hire charge is £10. <br> (ii) Find the Number of days, when the Total Cost is £61 and the Hire charge is £7.  </p></div></div><div class="answer"><div class="answercontainer">Total Cost = Number of days × £6.75 + Hire charge.</div><div class="answertext"><p>(i) 3 x 6.75 + 10 <br>(ii) 61 - 7 = 54, 54 ÷ 6.75 = 8</p></div></div></a>',
'06-12-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">MathMl: equations (see question Aut09-185/12-4(b))</div><div class="questiontext"><p>Write down the value of</p></div></div><div class="answer"><div class="answercontainer">MathMl: equations (see question Aut09-185/12-4(b))</div><div class="answertext"><p>(i) 29.16 (ii) 4.6</p></div></div></a>',
'06-13-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut09_185_12_5a.png"></div><div class="questiontext"><p>Write down the coordinates of the points A and B. Coordinates of A are (? , ?) Coordinates of B are (?, ?)</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut09_185_12_5a.png"></div><div class="answertext"><p>A(-3, 4)  B(-3, -2)</p></div></div></a>',
'06-14-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut09_185_12_7a.png"></div><div class="questiontext"><p>Calculate the perimeter of the rectangle above. What is the length of a side of a square that has a perimeter equal to that of the rectangle?</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut09_185_12_7a.png"></div><div class="answertext"><p>(a) (i) 9 + 9 + 4 + 4 = 26cm   (ii) 26 ÷ 4 = 6.5cm</p></div></div></a>',
'06-15-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut09_185_12_7b.png"></div><div class="questiontext"><p>Calculate the area of the rectangle.  What is the length of a side of a square that has an area equal to that of the rectangle?</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut09_185_12_7b.png"></div><div class="answertext"><p>(b)(i) 9 x 4 = 36cm2 (ii) √36 = 6</p></div></div></a>',
'06-16-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut09_185_12_9ai.png"></div><div class="questiontext"><p>A donkey weighs x kg. During the year the donkey’s weight increases by 8 kg.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut09_185_12_9ai.png"></div><div class="answertext"><p>x + 8</p></div></div></a>',
'06-17-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut09_185_12_9aii.png"></div><div class="questiontext"><p>A pencil costs 32 pence.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut09_185_12_9aii.png"></div><div class="answertext"><p>32g</p></div></div></a>',
'06-18-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">(i) 48, 42, 36, 30, ? </div><div class="questiontext"><p>Describe in words the rule for continuing the sequence above.</p></div></div><div class="answer"><div class="answercontainer">(i) 48, 42, 36, 30, ? </div><div class="answertext"><p>subtract six </p></div></div></a>',
'06-19-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">(ii) 2, 8, 32, 128, ?</div><div class="questiontext"><p>Describe in words the rule for continuing the sequence above.</p></div></div><div class="answer"><div class="answercontainer">(ii) 2, 8, 32, 128, ?</div><div class="answertext"><p>multiply by four</p></div></div></a>',
'06-20-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">(i) 6x = 48 <br> (ii) y + 6 = 19</div><div class="questiontext"><p>Solve each of the equations above.</p></div></div><div class="answer"><div class="answercontainer">(i) 6x = 48 <br> (ii) y + 6 = 19</div><div class="answertext"><p>(i) 48÷6  = 8, x=8  (ii) 19 - 6 =13, y = 13</p></div></div></a>',
'06-21-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut09_185_13_4.png"></div><div class="questiontext"><p>The diagram shows a triangle DEF with EF = 11cm, DXF = 90° and DX = 7cm.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut09_185_13_4.png"></div><div class="answertext"><p>7 × 11 = 77. 77 ÷ 2 = 38.5cm²</p></div></div></a>',
'06-22-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">MathMl: equation 6xsquared + 18xy....Aut09-185/14-13(a)</div><div class="questiontext"><p>Factorise the equation above.</p></div></div><div class="answer"><div class="answercontainer">MathMl: equation 6xsquared + 18xy....Aut09-185/14-13(a)</div><div class="answertext"><p>6x(x + 3y)</p></div></div></a>',
'06-23-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">MathMl: equation (see question Aut09-185/14-13(b))</div><div class="questiontext"><p>Simplify the equation above.</p></div></div><div class="answer"><div class="answercontainer">MathMl: equation (see question Aut09-185/14-13(b))</div><div class="answertext"><p>2(x + 3)</p></div></div></a>',
'06-24-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">MathMl: equation xsquared – 25. Aut09-185/14-13(c)</div><div class="questiontext"><p>Factorise the equation above.</p></div></div><div class="answer"><div class="answercontainer">MathMl: equation xsquared – 25. Aut09-185/14-13(c)</div><div class="answertext"><p>(x - 5)(x + 5)</p></div></div></a>',
'06-25-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">TBD - Image to be decided</div><div class="questiontext"><p>Express 104 as a percentage of 260.</p></div></div><div class="answer"><div class="answercontainer">TBD - Image to be decided</div><div class="answertext"><p>40%</p></div></div></a>',
'06-26-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">5.6* 3.4 / 8.1 - 2. 7</div><div class="questiontext"><p>Calculate the equation above, giving your answer correct to two decimal places.</p></div></div><div class="answer"><div class="answercontainer">5.6* 3.4 / 8.1 - 2. 7</div><div class="answertext"><p>3.53</p></div></div></a>',
'06-27-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut09_185_14_6c.png"></div><div class="questiontext"><p>Two friends share £280 in the ratio 3 : 4. Find how much each friend receives.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut09_185_14_6c.png"></div><div class="answertext"><p>3+ 4 = 7, 280÷7 = 40, the value of one part is £40, 40 x 3, 40 x 4</p></div></div></a>',
'06-28-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut11_185_08_13c.png"></div><div class="questiontext"><p>What is the output from the machine when the input is –3?</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut11_185_08_13c.png"></div><div class="answertext"><p>if -3 is the input, -3 + 7 = 4, 4÷2 = 2</p></div></div></a>',
'06-29-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">W = 2L + 3M</div><div class="questiontext"><p>Use the formula shown above  to find M when W = 35 and L = 4.</p></div></div><div class="answer"><div class="answercontainer">W = 2L + 3M</div><div class="answertext"><p>35 = 2 x 4 + 3M, 35 = 8 + 3M, 27 = 3M, M = 27÷3 = 9</p></div></div></a>',
'06-30-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut11-185-08-15a.png"></div><div class="questiontext"><p>The number of goals scored in 40 matches were noted. The results are summarised in the table above.   </p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut11-185-08-15a.png"></div><div class="answertext"><p>11/40 at least 2 inlcudes 2, therefore 6 + 4 + 1 = 11, 11 out of 40</p></div></div></a>',


/*JULY*/


'07-01-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut11_185_08_16a.png"></div><div class="questiontext"><p>Calculate the internet price of this tumble drier.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut11_185_08_16a.png"></div><div class="answertext"><p>17÷100x269 = £45.73, 269 - 45.73=£223.27</p></div></div></a>',

'07-02-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">MathMl: equation (see question) Aut11-185/08-18(a) <br><m:math display=”block”><m:mrow><m:mfrac><m:mrow><m:mn>14</m:mn><m:mo>&#x22C5;</m:mo><m:mn>5</m:mn><m:mo>&#x00D7;</m:mo><m:mn>33</m:mn><m:mo>&#x22C5;</m:mo><m:mn>4</m:mn></m:mrow><m:mrow><m:mn>710</m:mn><m:mo>&#x22C5;</m:mo><m:mn>7</m:mn><m:mo>&#x2212;</m:mo><m:mn>35.9</m:mn></m:mrow> </m:mfrac></m:mrow></m:math></div><div class="questiontext"><p>Find the above equation correct to two decimal places.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/cool-boots.png"></div><div class="answertext"><p>0.72</p></div></div></a>',

'07-03-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">(i) the distance from Milan to  Venice? <br> (ii) the weight of a person? <br> (iii) the volume of a bucket? <br> (iv) the length of a classroom?</div><div class="questiontext"><p>Write down the metric unit best used to measure</p></div></div><div class="answer"><div class="answercontainer">(i) the distance from Milan to  Venice? <br> (ii) the weight of a person? <br> (iii) the volume of a bucket? <br> (iv) the length of a classroom?</div><div class="answertext"><p> km,  kg,  litre,  m</p></div></div></a>',
'07-04-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut11_185_08_20a.png"></div><div class="questiontext"><p>Calculate the area of the trapezium.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut11_185_08_20a.png"></div><div class="answertext"><p>The area of a trapezium is: 1/2(a+b)xh, 1/2(8.2+12.8) x 7.6, 1/2(21) x 7.6, 10.5 x 7.6 =79.8cm2</p></div></div></a>',
'07-05-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut11_185_08_3.png"></div><div class="questiontext"><p>Katherine wants to find the weight of a small sweet. A tube with 40 of the sweets is put on the scale. How much does the tube weigh? She pours out the sweets and weighs the empty tube. How much does the empty tube weigh? Find the weight of one small sweet.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut11_185_08_3.png"></div><div class="answertext"><p>430, 190, 430 - 190 = 240, 240 ÷40 =6</p></div></div></a>',
'07-06-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">Wage = Number of hours of overtime × £15 + Basic pay</div><div class="questiontext"><p>A person’s weekly wage is worked out using the formula above. (i) Find a person’s Wage when the Number of hours of overtime is 7 and the Basic pay is £150. (ii) Find the Number of hours of overtime, when the Wage is £270 and the Basic pay is £180.</p></div></div><div class="answer"><div class="answercontainer">Wage = Number of hours of overtime × £15 + Basic pay</div><div class="answertext"><p>(a) 7 x 15 + 150  =255 (b) 270 = ? X 15 + 180, 270 - 180 = ? X 15, 90 = ? X 15, ? = 90÷15=6</p></div></div></a>',
'07-07-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut11_185_08_6a.png"></div><div class="questiontext"><p>On the probability scale shown above, mark the points A, B and C where: A is the probability of there being snow at the North Pole in December. B is the probability of it raining for 3 consecutive days, in August 2012, in the Sahara desert. C is the probability of the score being an odd number when a fair dice is thrown.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut11_185_08_6a.png"></div><div class="answertext"><p>Need image showing correct positions on scale</p></div></div></a>',
'07-08-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">nsquared – 6.</div><div class="questiontext"><p>The nth term of a sequence is shown above. Write down the first three terms of the sequence.</p></div></div><div class="answer"><div class="answercontainer">nsquared – 6.</div><div class="answertext"><p><m:math display="block"><m:mtable columnalign="left"><m:mtr><m:mtd><m:msup><m:mtext>1</m:mtext><m:mtext>2</m:mtext></m:msup><m:mtext>&#x00A0;-6&#x00A0;=&#x00A0;-5,&#x00A0;&#x00A0;</m:mtext></m:mtd></m:mtr><m:mtr><m:mtd><m:msup><m:mtext>2</m:mtext><m:mtext>2</m:mtext></m:msup><m:mtext>-6,=-2&#x00A0;</m:mtext></m:mtd></m:mtr><m:mtr><m:mtd><m:msup><m:mtext>3</m:mtext><m:mtext>2</m:mtext></m:msup><m:mtext>&#x00A0;-&#x00A0;6=3</m:mtext></m:mtd></m:mtr></m:mtable></m:math></p></div></div></a>',
'07-09-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">MathMl: equation (see question Aut11-185/10-2(b))</div><div class="questiontext"><p>Factorise the equation above.</p></div></div><div class="answer"><div class="answercontainer">MathMl: equation (see question Aut11-185/10-2(b))</div><div class="answertext"><p>x(x - 5)</p></div></div></a>',
'07-10-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">MathMl: equation (see question Aut11-185/10-2(c))</div><div class="questiontext"><p>Factorise the equation above.</p></div></div><div class="answer"><div class="answercontainer">MathMl: equation (see question Aut11-185/10-2(c))</div><div class="answertext"><p>120(2y - 3)</p></div></div></a>',
'07-11-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">MathMl: equation (see question Aut11-185/10-2(d))</div><div class="questiontext"><p>Solve the equation above.</p></div></div><div class="answer"><div class="answercontainer">MathMl: equation (see question Aut11-185/10-2(d))</div><div class="answertext"><p>12x - 44 = 40, 12x = 84, x = 84÷12 = 7</p></div></div></a>',
'07-12-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">MathMl: equation (see question Aut11-185/10-2(e))</div><div class="questiontext"><p>Solve the equation above.</p></div></div><div class="answer"><div class="answercontainer">MathMl: equation (see question Aut11-185/10-2(e))</div><div class="answertext"><p>x=9</p></div></div></a>',
'07-13-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">MathMl: equation (see question Aut11-185/10-3(a))</div><div class="questiontext"><p>Find the above equation correct to two decimal places.</p></div></div><div class="answer"><div class="answercontainer">MathMl: equation (see question Aut11-185/10-3(a))</div><div class="answertext"><p>Aut11-185/10-3(a)</p></div></div></a>',
'07-14-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">76 million = ???? Aut11-185/10-7(b)(i)</div><div class="questiontext"><p>Write 76 million in standard form.</p></div></div><div class="answer"><div class="answercontainer">76 million = ????</div><div class="answertext"><p>MathMl: 7.6 x 10 7</p></div></div></a>',
'07-15-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">MathMl: equation (see question Aut11-185/10-7(b)(ii))</div><div class="questiontext"><p>Find, in standard form, the value of the equation above</p></div></div><div class="answer"><div class="answercontainer">MathMl: equation (see question Aut11-185/10-7(b)(ii))</div><div class="answertext"><p>8 x 108</p></div></div></a>',

'07-16-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut11-185-12-1c-i-ii.png"></div><div class="questiontext"><p>(i) What percentage of the pattern is shaded? (ii) What percentage of the pattern is NOT shaded?</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut11-185-12-1c-i-ii.png"></div><div class="answertext"><p>(i) 40%  (ii) 60%</p></div></div></a>',

'07-17-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut11_185_12_10ab.png"></div><div class="questiontext"><p>Hywel and Janet go on holiday to the USA. They change £1300 into dollars ($) when the exchange rate was £1 = $1.55. How many dollars did they get? On their return they have $363 left over. They change this back into pounds when the rate of exchange is £1 = $1.65. How much do they get in pounds?</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut11_185_12_10ab.png"></div><div class="answertext"><p>(a) Using Pythagoras theorem, AD2 = BD2 - AB2 = 12.32 - 6.22, AD2 = 112.85, AD = √112.85 = 10.6cm        (b) 37.5cm2</p></div></div></a>',

'07-18-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">MathMl: equation (see question Aut11-185/12-12(a))</div><div class="questiontext"><p>Simplify the equation above.</p></div></div><div class="answer"><div class="answercontainer">MathMl: equation (see question Aut11-185/12-12(a))</div><div class="answertext"><p>(a) y = kx2, 4 = k x 0.52, k = 4 ÷0.25, k = 16 <br> y = 16xsquared</p></div></div></a>',

'07-19-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">TBD</div><div class="questiontext"><p>The sum of seven, single digit positive whole numbers is 17.</p></div></div><div class="answer"><div class="answercontainer">TBD</div><div class="answertext"><p>5, 6 x 2 = 12, need +5 to make 17</p></div></div></a>',

'07-20-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut11_185_12_2.png"></div><div class="questiontext"><p>A box is placed on a scale. Sand is poured into the box. Find how much the sand weighs.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut11_185_12_2.png"></div><div class="answertext"><p>920 - 280 = 640g</p></div></div></a>',
'07-21-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut11_185_12_4a.png"></div><div class="questiontext"><p>Write down the special name of the straight line shown in both the diagrams.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut11_185_12_4a.png"></div><div class="answertext"><p>diameter, tangent</p></div></div></a>',
'07-22-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut11_185_12_4b.png"></div><div class="questiontext"><p>Write down the name of each of the shapes shown</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut11_185_12_4b.png"></div><div class="answertext"><p>1st row: pentagon, cylinder 2nd row: triangular prism</p></div></div></a>',
'07-23-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">Value of the Number = 5 × Position of the Number + 6</div><div class="questiontext"><p>A list of numbers is made by using the formula above  (i) Find the Value of the Number when the Position of the Number is 9. (ii) Find the Position of the Number when the Value of the Number is 121.</p></div></div><div class="answer"><div class="answercontainer">Value of the Number = 5 × Position of the Number + 6</div><div class="answertext"><p>(a) 5 x 9 + 6  =51                (b) 121 - 6 = 115, 115÷5=23</p></div></div></a>',
'07-24-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut11_185_12_9aii.png"></div><div class="questiontext"><p>Geoff is t cm tall. Jill is 6 cm taller than Geoff. Write down, in terms of t, Jill’s height.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut11_185_12_9aii.png"></div><div class="answertext"><p>t + 6</p></div></div></a>',



'07-25-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">SVG/PNG of concrete block</div><div class="questiontext"><p>Concrete blocks each weigh w kg. Write down, in terms of w, the weight of 10 blocks.</p></div></div><div class="answer"><div class="answercontainer">SVG/PNG of concrete block</div><div class="answertext"><p>10w</p></div></div></a>',





'07-26-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut11_185_12_9aii.png"></div><div class="questiontext"><p>Mary is x years old.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut11_185_12_9aii.png"></div><div class="answertext"><p>x - 5</p></div></div></a>',




'07-27-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/cool-boots.png"></div><div class="questiontext"><p>Question will appear here!</p></div></div><div class="answer"><div class="answercontainer"><img src="images/cool-boots.png"></div><div class="answertext"><p>Answer will appear here!</p></div></div></a>',
'07-28-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/cool-boots.png"></div><div class="questiontext"><p>Question will appear here!</p></div></div><div class="answer"><div class="answercontainer"><img src="images/cool-boots.png"></div><div class="answertext"><p>Answer will appear here!</p></div></div></a>',

'07-29-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/cool-boots.png"></div><div class="questiontext"><p>Question will appear here!</p></div></div><div class="answer"><div class="answercontainer"><img src="images/cool-boots.png"></div><div class="answertext"><p>Answer will appear here!</p></div></div></a>',
'07-30-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/cool-boots.png"></div><div class="questiontext"><p>Question will appear here!</p></div></div><div class="answer"><div class="answercontainer"><img src="images/cool-boots.png"></div><div class="answertext"><p>Answer will appear here!</p></div></div></a>',





'07-30-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/cool-boots.png"></div><div class="questiontext"><p>Question will appear here!</p></div></div><div class="answer"><div class="answercontainer"><img src="images/cool-boots.png"></div><div class="answertext"><p>Answer will appear here!</p></div></div></a>',


'08-30-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><p style="text-align: left;">(i)</p><math><semantics><mrow><msqrt><mrow><mn>11.56</mn></mrow></msqrt></mrow></semantics></math><p style="text-align: left;">(ii)</p><math><semantics><mrow><msup><mrow><mn>5.4</mn></mrow><mn>2</mn></msup></mrow></semantics></math></div></div><div class="answer"><div class="answercontainer"><img src="images/maths-test-01.png"></div><div class="answertext"><p>Answer will appear here!</p></div></div></a>',

	'02-21-2014' : '<a href="http://tympanus.net/codrops/2012/11/21/adaptive-thumbnail-pile-effect-with-automatic-grouping/">Adaptive Thumbnail Pile Effect with Automatic Grouping</a>',

	'12-25-YYYY' : '<a href="#"><span>Christmas Day</span></a>',
	'12-31-YYYY' : '<a href="#"><span>New Year\'s Eve</span></a>'

};