var codropsEvents = {

/*April */	


'04-01-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><p style="text-align: left;">(i)</p><math><semantics><mrow><msqrt><mrow><mn>11.56</mn></mrow></msqrt></mrow></semantics></math><p style="text-align: left;">(ii)</p><math><semantics><mrow><msup><mrow><mn>5.4</mn></mrow><mn>2</mn></msup></mrow></semantics></math></div><div class="questiontext"><p>Write down the value of the above</p></div></div><div class="answer"><div class="answercontainer"><p style="text-align: left;">(i)</p><math><semantics><mrow><msqrt><mrow><mn>11.56</mn></mrow></msqrt></mrow></semantics></math><p style="text-align: left;">(ii)</p><math><semantics><mrow><msup><mrow><mn>5.4</mn></mrow><mn>2</mn></msup></mrow></semantics></math></div><div class="answertext"><p>Answer will appear here!</p></div></div></a>',
'04-02-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><math><semantics><mrow><mo stretchy="false">(</mo><mn>5.4</mn><mo>&#x00D7;</mo><msup><mrow><mn>10</mn></mrow><mn>3</mn></msup><mo stretchy="false">)</mo><mo>&#x00D7;</mo><mo stretchy="false">(</mo><mn>3</mn><mo>&#x00D7;</mo><msup><mrow><mn>10</mn></mrow><mn>5</mn></msup><mo stretchy="false">)</mo></mrow></semantics></math><div class="questiontext"><p>Question</p></div></div></div><div class="answer"><div class="answercontainer"><p>Answer will appear here!</p></div><div class="answertext"><p>Answer will appear here!</p></div></div></a>',
'04-03-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut07_181_01_1a.png"><p>Geraint buys a pair of jeans for £22.49 and a polo shirt for £13.87.</p></div><div class="questiontext"><p> Find the total cost of these two items.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut07_181_01_1a.png"><p>Geraint buys a pair of jeans for £22.49 and a polo shirt for £13.87.</p></div><div class="answertext"><p>£22.49 + £13.87 = £36.36</p></div></div></a>',
'04-04-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut07_181_01_10.png"><p>The diagram above shows a right-angled triangle with one angle of 67°.</p></div><div class="questiontext"><p>Find the value of x?</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut07_181_01_10.png"  ></div><div class="answertext"><p>180° - 90° - 67° = 23°</p></div></div></a>',
'04-05-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut07_181_01_4b.png"><p>The bar chart shows the number of pupils absent each day in a particular week.</p></div><div class="questiontext"><p> How many absences, in total, were recorded for that week?</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut07_181_01_4b.png"  ><p>The bar chart shows the number of pupils absent each day in a particular week.</p></div><div class="answertext"><p>How many absences, in total, were recorded for that week? 4+5+2+3+4 = 18</p></div></div></a>',
'04-06-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut07_181_01_5a.png"></div><div class="questiontext"><p>Write down the two lines in the above diagram,<br> which are perpendicular to each other.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut07_181_01_5a.png"></div><div class="answertext"><p>AB, BC <br>(Two lines are perpendicular if they meet at a right angle, or at 90°)</p></div></div></a>',
'04-07-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut07_181_01_7b.png"></div><div class="questiontext"><p>Write down the area of the rectangle shown above.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut07_181_01_7b.png"></div><div class="answertext"><p>5cm × 7cm = 35cm²</p></div></div></a>',
'04-08-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><p><math><mrow><mn>4</mn><mi>a</mi><mtext>&#x00A0;</mtext><mo>+</mo><mtext>&#x00A0;</mtext><mn>7</mn><mi>a</mi><mtext>&#x00A0;</mtext><mo>+</mo><mtext>&#x00A0;</mtext><mn>8</mn><mi>a</mi></mrow></math></p></div><div class="questiontext"><p>Simplify the equation above.</p></div></div><div class="answer"><div class="answercontainer"><p><math><mrow><mn>4</mn><mi>a</mi><mtext>&#x00A0;</mtext><mo>+</mo><mtext>&#x00A0;</mtext><mn>7</mn><mi>a</mi><mtext>&#x00A0;</mtext><mo>+</mo><mtext>&#x00A0;</mtext><mn>8</mn><mi>a</mi></mrow></math></p></div><div class="answertext"><p><math><mrow><mn>19</mn><mi>a</mi></mrow></math></p></div></div></a>',
'04-09-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><p><img src="images/cool-boots.png"></p></div><div class="questiontext"><p>Write down the value of the cube of 5.</p></div></div><div class="answer"><div class="answercontainer"><p><img src="images/cool-boots.png"></p></div><div class="answertext"><p>5³ = 5 × 5 × 5 = 25 × 5 = 125.</p></div></div></a>',
'04-10-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><p>1 4 9 16</p></div><div class="questiontext"><p>Write down, in terms of n, the nth term of the sequence shown above.</p></div></div><div class="answer"><div class="answercontainer"><p>1 4 9 16</p></div><div class="answertext"><p>n squared</p></div></div></a>',
'04-11-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><p><table><tr><th>Name of three-dimensional solid</th><th>Number of triangular faces</th><th>Number of square rectangler faces</th><th>Number of exagonal faces</th></tr><tr><td>Square- based pyramid</td><td></td><td></td><td></td></tr><tr><td>Tetrahedron</td><td></td><td></td><td></td></tr><tr><td>Hexagonal prism</td><td></td><td></td><td></td></tr></table></p></div><div class="questiontext"><p>Complete the table shown above.</p></div></div><div class="answer"><div class="answercontainer"><p><table><tr><th>Name of three-dimensional solid</th><th>Number of triangular faces</th><th>Number of square rectangler faces</th><th>Number of exagonal faces</th></tr><tr><td>Square- based pyramid</td><td>4</td><td>1</td><td>0</td></tr><tr><td>Tetrahedron</td><td>4</td><td>0</td><td>0</td></tr><tr><td>Hexagonal prism</td><td>0</td><td>6</td><td>2</td></tr></table></p></div></div></a>',
'04-12-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><p>0.2 x 0.3</p></div><div class="questiontext"><p>Find the value of the equation shown above</p></div></div><div class="answer"><div class="answercontainer"><p>0.2 x 0.3</p></div><div class="answertext"><p>2/10 × 3/10 = 6/100 = 0.06</p></div></div></a>',
'04-13-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut07_184_05_10a.png"><p>In the diagram above, ABCD is a trapezium with AD parallel to BC. The lengths of AD and BC are 30cm and 20cm respectively. The perpendicular distance between the parallel sides is 22cm.</p></div><div class="questiontext"><p> Calculate the area of the trapezium and clearly write down the units of your answer.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut07_184_05_10a.png"></div><div class="answertext"><p>20 + 30 = 50. 50 ÷ 2 = 25. 25 × 22 = 550cm²</p></div></div></a>',
'04-14-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/cool-boots.png"></div><div class="questiontext"><p>Convert 54 000 cm2 into m2.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/cool-boots.png"></div><div class="answertext"><p>54000 ÷ 100 = 540. 540 ÷ 100 = 5.4 m². <br> With area we must divide by the scale factor (100) twice.</p></div></div></a>',
'04-15-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><p><table><tr><td>x</td><td>-2</td><td>-1</td><td>0</td><td>1</td><td>2</td><td>3</td></tr><tr><td><math><mrow><mi>y</mi><mo>=</mo><mn>3</mn><msup><mi>x</mi><mn>3</mn></msup><mtext>&#x00A0;</mtext><mo>&#x2212;</mo><mtext>&#x00A0;</text><mn>4</mn><mi>x</mi><mtext>&#x00A0;</mtext><mo>&#x2212;</mo><mtext>&#x00A0;</mtext><mn>10</mn></mrow></math></td><td>10</td><td></td><td>-10</td><td>-11</td><td>-6</td><td>5</td></tr></table></p></div><div class="questiontext"><p>The table shows some of the values of y = 3x2 – 4x – 10 for values of x between – 2 and 3.</p></div></div><div class="answer"><div class="answercontainer"><p><table><tr><td>x</td><td>-2</td><td>-1</td><td>0</td><td>1</td><td>2</td><td>3</td></tr><tr><td><math><mrow><mi>y</mi><mo>=</mo><mn>3</mn><msup><mi>x</mi><mn>3</mn></msup><mtext>&#x00A0;</mtext><mo>&#x2212;</mo><mtext>&#x00A0;</text><mn>4</mn><mi>x</mi><mtext>&#x00A0;</mtext><mo>&#x2212;</mo><mtext>&#x00A0;</mtext><mn>10</mn></mrow></math></td><td>10</td><td></td><td>-10</td><td>-11</td><td>-6</td><td>5</td></tr></table></p></div><div class="answertext"><p>3 × (-1)² - 4 × -1 - 10 = 3 × 1 - -4 - 10 = 3 + 4 - 10 = -3</p></div></div></a>',
'04-16-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><p>Find the Value of <br><math display="block"><mrow><mfrac><mn>5</mn><mn>6</mn></mfrac><mo>&#x2212;</mo><mfrac><mn>1</mn><mn>4</mn></mfrac></mrow></math></p></div></div><div class="answer"><div class="answercontainer"><math display="block"><mrow><mfrac><mn>5</mn><mn>6</mn></mfrac><mo>&#x2212;</mo><mfrac><mn>1</mn><mn>4</mn></mfrac><mo>=</mo><mfrac><mrow><mn>10</mn></mrow><mrow><mn>12</mn></mrow></mfrac><mo>&#x2212;</mo><mfrac><mn>3</mn><mrow><mn>12</mn></mrow></mfrac><mo>=</mo><mfrac><mn>7</mn><mrow><mn>12</mn></mrow></mfrac></mrow></math></div></div></a>',
'04-17-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut07_184_05_3c.png"></div><div class="questiontext"><p>Calculate, in mph, the speed of a motorcyclist who travels 154 miles in 3 hours, 30 minutes.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut07_184_05_3c.png"></div><div class="answertext"><p>154 ÷ 3.5 = 44 m.p.h.</p></div></div></a>',
'04-18-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut07_184_05_5b.png"></div><div class="questiontext"><p>Find the size of the angle marked y.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut07_184_05_5b.png"></div><div class="questiontext"><p>115° + 88° + 82° = 285°. 360° - 285° = 75°. 180° - 75° = 105°</p></div></div></a>',
'04-19-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><p>Write each of the following numbers in standard form.<br> (i) 0·0083 <br>(ii) 7 500000000</p></div></div><div class="answer"><div class="answercontainer"> <math display="block"><mrow><mo stretchy="false">(</mo><mi>i</mi><mo stretchy="false">)</mo><mtext>&#x00A0;</mtext><mn>4.98</mn><mtext>&#x00A0;</mtext><mi>x</mi><mtext>&#x00A0;</mtext><msup><mrow><mn>10</mn></mrow><mrow><msup><mrow></mrow><mrow><mn>7</mn><mtext>&#x00A0;&#x00A0;&#x00A0;</mtext></mrow></msup></mrow></msup><mtext>&#x00A0;&#x00A0;&#x00A0;&#x00A0;&#x00A0;&#x00A0;&#x00A0;&#x00A0;</mtext><mo stretchy="false">(</mo><mi>i</mi><mi>i</mi><mo stretchy="false">)</mo><mn>3</mn><mtext>&#x00A0;</mtext><mi>x</mi><mtext>&#x00A0;</mtext><mn>10</mn><msup><mtext>&#x00A0;</mtext><mrow><mo>-</mo><mn>6</mn></mrow></msup></mrow></math></div></div></a>',
'04-20-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><p>Find, in standard form, the value of</p><br> <math display="block"><mrow><mo stretchy="false">(</mo><mn>2.66</mn><mo>&#x00A0;</mo><mo>&#x00D7;</mo><msup><mrow>    <mn>10</mn></mrow><mn>9</mn></msup><mo stretchy="false">)</mo><mo>&#x00F7;</mo><mo stretchy="false">(</mo><mn>7.6</mn><mo>&#x00D7;</mo><msup><mrow><mn>10</mn></mrow><mrow><mo>&#x2212;</mo><mn>3</mn></mrow></msup><mo stretchy="false">)</mo></mrow></math></div></div><div class="answer"><div class="answercontainer"><math display="block"><mrow><mtext>8</mtext><msup><mrow><mtext>.846&#x00A0;x&#x00A0;10</mtext></mrow><mtext>9</mtext></msup></mrow></math></div></div></a>',
'04-21-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><math display="block"><mrow><mtext>2</mtext><mfrac><mn>1</mn><mn>4</mn></mfrac><mo>&#x00D7;</mo><mn>3</mn><mfrac><mn>1</mn><mn>3</mn></mfrac></mrow></math></div></div><div class="answer"><div class="answercontainer"><p>7½ ("The fraction 90/12 can be simplified to give 15/2, or 7½")</p></div></div></a>',


'MM-22-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><math display="block"><mrow><msup><mn>8</mn><mn>0</mn></msup></mrow></math></div><div class="questiontext"><p>Simplify the equation above.</p></div></div><div class="answer"><div class="answercontainer"><math display="block"><mrow><msup><mn>8</mn><mn>0</mn></msup></mrow></math></div><div class="answertext"><p>Any number to the power 0 is equal to 1.</p></div></div></a>',


'MM-23-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><p>There are 100 pupils in Year 9. The time taken by each pupil to answer a mental mathematics</p><img src="images/Aut07-184-09-19a.png"></div><div class="questiontext"><p>Find an estimate of this distribution</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut07-184-09-19a.png"></div><div class="answertext"><p>100 ÷ 2 = 50.<br> There are 50 pupils in the first three groups, and 50 in the final two groups.<br> The median is therefore 30 seconds.</p></div></div></a>',


'MM-24-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/money-notes-uk.jpg"></div><div class="questiontext"><p>Find 40% of £120.</p></div></div><div class="answer"><div class="answercontainer"> <img src="images/money-notes-uk.jpg"></div><div class="answertext"><p>10% of £120 = £12. So 40% of £120 is   4 × £12 = £48.</p></div></div></a>',


'MM-25-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><p><br><math display="block"><mrow><msup><mrow><mo stretchy="false">(</mo><mn>0.5</mn><mo stretchy="false">)</mo></mrow><mn>2</mn></msup></mrow></math></div><div class="questiontext"><p>Write down the value of the equation above</p></div></div><div class="answer"><div class="answercontainer"><math display="block"><mrow><msup><mrow><mo stretchy="false">(</mo><mn>0.5</mn><mo stretchy="false">)</mo></mrow><mn>2</mn></msup><mtext>=&#x00A0;0</mtext><mtext>.5</mtext><mo>&#x00D7;</mo><mn>0.5</mn><mo stretchy="false">(</mo><mfrac>  <mn>1</mn><mn>2</mn></mfrac><mo>&#x00D7;</mo><mfrac><mn>1</mn><mn>2</mn></mfrac><mo>=</mo><mfrac><mn>1</mn><mn>4</mn>  </mfrac><mo stretchy="false">)</mo></mrow></math></div></div></a>',

'MM-26-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/cool-boots.png"></div><div class="questiontext"><p>Steven has £50 to spend on computer games. Each game costs £7.89.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/cool-boots.png"></div><div class="answertext"><p>50÷7.79 = 6.337, so 6 whole games</p></div></div></a>',


'MM-27-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/cool-boots.png"></div><div class="questiontext"><p>Sarah buys 4 CDs. They cost £5.86 each. How much change will she be given from £30?</p></div></div><div class="answer"><div class="answercontainer"><img src="images/cool-boots.png"></div><div class="answertext"><p>4 x 5.86 = 23.44  30 - 23.44 = £6.56</p></div></div></a>',


'MM-28-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/cool-boots.png"></div><div class="questiontext"><p>Write down the name of a four-sided shape which has rotational symmetry of order 4.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/cool-boots.png"></div><div class="answertext"><p>square</p></div></div></a>',


'MM-29-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut08_181_02_13a.png"  ></div><div class="questiontext"><p>Write down the size of the angle marked x in the following diagram.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut08_181_02_13a.png"></div><div class="answertext"><p>128</p></div></div></a>',

'MM-30-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut08_181_02_13b.png"  ></div><div class="questiontext"><p>Calculate the area of the triangle shown above.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut08_181_02_13b.png"></div><div class="answertext"><p>Area of a triangle is 1/2(base x height), 1/2(12 x 8) = 1/2(96)=48cm2</p></div></div></a>',


'MM-31-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/money-notes-uk.jpg"></div><div class="questiontext"><p>3 8 11 16 19 24 27 From the list of numbers given above: write down a square number write down a multiple of 6 write down a factor of 40 </p></div></div><div class="answer"><div class="answercontainer"><p>from top: 16, 24, 8</p></div></div></a>',


/*MAY */	



'05-01-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/cool-boots.png"></div><div class="questiontext"><p>Write 2472<br>(i) correct to the nearest 10 <br>(ii) correct to the nearest 100</div></div><div class="answer"><div class="answercontainer"><img src="images/cool-boots.png"></div><div class="answertext"><p>Answer will appear here!</p></div></div></a>',

'05-02-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut07_181_02_5.png"></div><div class="questiontext"><p>Write down two pairs of congruent shapes from the diagrams above.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut07_181_02_5.png"></div><div class="answertext"><p>B and I, E and J</p></div></div></a>',

'05-03-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><p>(i) 3, 9, 15, 21, ????<br> (ii) 20, 17, 14, 11, ????</p></div><div class="questiontext"><p> <br> Write down the next number in the sequences above. </p></div></div><div class="answer"><div class="answercontainer"><p>(i) 3, 9, 15, 21, ????<br> (ii) 20, 17, 14, 11, ????</p></div><div class="answertext"><p>(i) rule is  + 6   = 27 <br>(ii) rule is -3 = 8</p></div></div></a>',

'05-04-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><p>2, 9, 16, 23,</p></div><div class="questiontext"><p>Describe, in words, the rule for finding the next number in the sequence given above.</p></div></div><div class="answer"><div class="answercontainer"><p>2, 9, 16, 23,</p></div><div class="answertext"><p>add seven </p></div></div></a>',

'05-05-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><p>Cost = £35 × Number of Hours + Call-out Charge</p></div><div class="questiontext"><p>The formula shown above is used to calculate the cost of repairing washing machines. Calculate the Cost when the Number of Hours is 3 and the Call-out Charge is £40.</p></div></div><div class="answer"><div class="answercontainer"><p>The formula shown above is used to calculate the cost of repairing washing machines. Calculate the Cost when the Number of Hours is 3 and the Call-out Charge is £40.</p></div><div class="answertext"><p>35 x 3 + 40 = £145</p></div></div></a>',

'05-06-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut08_181_02_8b.png"></div><div class="questiontext"><p>In the diagram shown above, AOB is a straight line.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut08_181_02_8b.png"></div><div class="answertext"><p>angles on a straight line add up to 180, 180 -  43 - 108 = 29</p></div></div></a>',

'05-07-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">MathMl of expression (see question)</div><div class="questiontext"><p>Find, correct to 3 significant figures, the value of the expression shown above.</p></div></div><div class="answer"><div class="answercontainer">MathMl of expression (see question)</div><div class="answertext"><p>5.62</p></div></div></a>',

'05-08-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><p>2a + 7b</p></div><div class="questiontext"><p>What is the value of  the equation above when a = 6 and b = –2?</p></div></div><div class="answer"><div class="answercontainer"><p>2a + 7b</p></div><div class="answertext"><p>2 x 6 + 7 x (-2) = 12 - 14 = -2</p></div></div></a>',

'05-09-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><p>32, 30, 26, 20, 12,</p></div><div class="questiontext"><p>Write down the next two numbers in the sequence shown above.</p></div></div><div class="answer"><div class="answercontainer"><p>32, 30, 26, 20, 12,</p></div><div class="answertext"><p>look at the difference between each term, -2, -4, -6,-8,  therefore -10 for the next term and -12 for the one after = 2,  -10</p></div></div></a>',

'05-10-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut08_181_04_5a.png"></div><div class="questiontext"><p>The diagram above represents a number machine.   <br> (i) When the INPUT is 7, what is the OUTPUT?  <br> (ii) When the OUTPUT is 30, what is the INPUT?  <br> (iii) If the INPUT is n, write down the OUTPUT in terms of n.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut08_181_04_5a.png"></div><div class="answertext"><p>(i)20 (ii) 9 (iii)5(n -3)</p></div></div></a>',

'05-11-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">MathMl: 5(2x – 3) = 20.</div><div class="questiontext"><p>Solve the equation above.</p></div></div><div class="answer"><div class="answercontainer">MathMl: 5(2x – 3) = 20.</div><div class="answertext"><p>10x = 35, x = 35÷10 = 3.5</p></div></div></a>',

'05-12-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">TBD</div><div class="questiontext"><p>Calculate, to 1 decimal place, the area of a circle whose radius is 12·3 cm, clearly stating the units of your answer.</p></div></div><div class="answer"><div class="answercontainer">Calculate, to 1 decimal place, the area of a circle whose radius is 12·3 cm, clearly stating the units of your answer.</div><div class="answertext"><p>Area of a circle = πr2, π x 12.32 = 475.3</p></div></div></a>',

'05-13-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">PIC WAITING - Aut08-181/04-7(a)</div><div class="questiontext"><p>A packet of nails costs £2 and a packet of screws costs £3. Andrew buys 4 packets of nails and x packets of screws for a total of £23.</p></div></div><div class="answer"><div class="answercontainer">PIC WAITING - Aut08-181/04-7(a)<p>A packet of nails costs £2 and a packet of screws costs £3. Andrew buys 4 packets of nails and x packets of screws for a total of £23.</p></div><div class="answertext"><p>8 + 3x = 23</p></div></div></a>',

'05-14-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">PIC WAITING - Aut08-184/05-7(b)</div><div class="questiontext"><p>Share £56 in the ratio of 6:1.</p></div></div><div class="answer"><div class="answercontainer">PIC WAITING - Aut08-184/05-7</div><div class="answertext"><p>6 + 1 = 7. £56 ÷ 7 = £8. £8 × 6 = £48. £8 × 1 = £8.</p></div></div></a>',

'05-15-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut08_810_01_4b.png"></div><div class="questiontext"><p>A bag contains 4 balls which are identical except for their colour. There is 1 red, 1 yellow, 1 blue and 1 green ball. One ball is chosen at random from the bag. On the probability scale shown below, mark the points, A, B and C where: A is the probability that the chosen ball is green. B is the probability that the chosen ball is white. C is the probability that the chosen ball is not green.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut08_810_01_4b.png"></div><div class="answertext"><p>Need to create diagram with B, A and C labelled.</p></div></div></a>',

'05-16-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">PIC WAITING - Aut09-185/08-1(a)</div><div class="questiontext"><p>Alice buys 3 packets of biscuits at £1.35 each and 2 bars of muesli at 56p each. How much is this altogether?</p></div></div><div class="answer"><div class="answercontainer">PIC WAITING - Aut09-185/08-1(a)</div><div class="answertext"><p>3 x 1.35 = 4.05, 2 x 0.56 = 1.12, 4.05 + 1.12 = £5.17</p></div></div></a>',

'05-17-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">4c + 2c + 3c.</div><div class="questiontext"><p>Simplify</p></div></div><div class="answer"><div class="answercontainer">4c + 2c + 3c</div><div class="answertext"><p>9c</p></div></div></a>',

'05-18-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"> <br>(i) 3x = 15 <br> <br>(ii) y + 7 = 13 <br></div><div class="questiontext"><p>Solve each of the following equations.</p></div></div><div class="answer"><div class="answercontainer"> <br>(i) 3x = 15 <br>(ii) y + 7 = 13 <br></div><div class="answertext"><p> <br>(i) x = 15 <br> <br>(ii) y = 6 <br></p></div></div></a>',

'05-19-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">MathMl: R = 3V + 2T (Aut09-185/08-12(c))</div><div class="questiontext"><p>Use the formula  to find V when R = 40 and T = 5.</p></div></div><div class="answer"><div class="answercontainer">MathMl: R = 3V + 2T (Aut09-185/08-12(c)</div><div class="answertext"><p>40 = 3V + 2 x 5, 40 = 3V + 10, 3V = 30, V = 30÷10</p></div></div></a>',

'05-20-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer">MathMl: formula (see question Aut09-185/08-15(b))</div><div class="questiontext"><p>Evaluate</p></div></div><div class="answer"><div class="answercontainer">MathMl: formula (see question Aut09-185/08-15(b))</div><div class="answertext"><p>24.09</p></div></div></a>',



'05-21-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/Aut09_185_08_18bii.png"></div><div class="questiontext"><p>The diagram shows a quadrilateral.</p></div></div><div class="answer"><div class="answercontainer"><img src="images/Aut09_185_08_18bii.png"></div><div class="answertext"><p> x = 7 ©7cm, 9cm, 10cm, 14cm in any order</p></div></div></a>',



'05-22-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/cool-boots.png"></div><div class="questiontext"><p>Question will appear here!</p></div></div><div class="answer"><div class="answercontainer"><img src="images/cool-boots.png"></div><div class="answertext"><p>Answer will appear here!</p></div></div></a>',


'05-23-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/cool-boots.png"></div><div class="questiontext"><p>Question will appear here!</p></div></div><div class="answer"><div class="answercontainer"><img src="images/cool-boots.png"></div><div class="answertext"><p>Answer will appear here!</p></div></div></a>',
'05-24-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><img src="images/cool-boots.png"></div><div class="questiontext"><p>Question will appear here!</p></div></div><div class="answer"><div class="answercontainer"><img src="images/cool-boots.png"></div><div class="answertext"><p>Answer will appear here!</p></div></div></a>',












'05-30-YYYY' : '<a href="#"><div class="question"><div class="questioncontainer"><p style="text-align: left;">(i)</p><math><semantics><mrow><msqrt><mrow><mn>11.56</mn></mrow></msqrt></mrow></semantics></math><p style="text-align: left;">(ii)</p><math><semantics><mrow><msup><mrow><mn>5.4</mn></mrow><mn>2</mn></msup></mrow></semantics></math></div></div><div class="answer"><div class="answercontainer"><img src="images/maths-test-01.png"></div><div class="answertext"><p>Answer will appear here!</p></div></div></a>',

	'02-21-2014' : '<a href="http://tympanus.net/codrops/2012/11/21/adaptive-thumbnail-pile-effect-with-automatic-grouping/">Adaptive Thumbnail Pile Effect with Automatic Grouping</a>',

	'12-25-YYYY' : '<a href="#"><span>Christmas Day</span></a>',
	'12-31-YYYY' : '<a href="#"><span>New Year\'s Eve</span></a>'

};